CREATE TABLE URI_REGISTRY  (
	NAME VARCHAR(255) NOT NULL PRIMARY KEY,
	URI VARCHAR(255) NOT NULL
);
CREATE TABLE EAV_REGISTRY_ATTRIBUTES  (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL
);
CREATE TABLE EAV_REGISTRY_ATTRIBUTE_VALUES  (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ATTRIBUTE_ID INT,
	NAMESPACE VARCHAR(255) NOT NULL,
	VALUE VARCHAR(255) NOT NULL
);
